# agents/store_analysis_agent.py

from langchain.agents import create_agent
from tools.analysis_storage_tool import AnalysisStorageTool


class StoreAnalysisAgent:

    def __init__(self, model: str = "openai:gpt-4.1", persist_directory: str = "vector_store"):
        self.model = model
        self.tools = AnalysisStorageTool(persist_directory).get_tools()
        self.name = "store_analysis_agent"

        self.description = (
            "Stores analysis results generated by other agents into the vector database. "
            "It accepts JSON analysis, summary, trend analysis, or any structured output "
            "and stores it using the tool `store_analysis_result`."
        )

    def create_agent(self):
        return create_agent(
            model=self.model,
            tools=self.tools,
            system_prompt=(
                "You are StoreAnalysisAgent.\n\n"

                "Your ONLY job is to store analysis results **into the vector database**.\n"
                "You will receive data in the following parameters:\n"
                "- `agent_name`: name of the agent that produced the analysis\n"
                "- `result_type`: e.g., 'trend_analysis', 'summary', 'video_summary'\n"
                "- `result`: the JSON (dict/string/list) to store\n"
                "- `doc_id`: identifier of the document/video\n"
                "- `metadata`: optional metadata\n\n"

                "IMPORTANT RULES:\n"
                "1. ALWAYS call the tool `store_analysis_result`.\n"
                "2. NEVER modify or rewrite the analysis JSON.\n"
                "3. NEVER output markdown, explanations, or JSON by yourself.\n"
                "4. After tool call, output a very short confirmation like:\n"
                "    'Analysis stored successfully.'\n"
                "5. If information is missing, ask for clarification.\n\n"

                "Your purpose is ONLY storage. Do NOT generate any analysis.\n"
            ),
            name=self.name
        )
